CREATE TABLE TB_PONTOS_COLETA (
    id_ponto NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    bairro VARCHAR2(50),
    peso_kg NUMBER,
    status VARCHAR2(20) DEFAULT 'PENDENTE' -- 'PENDENTE' ou 'COLETADO'
);

INSERT INTO TB_PONTOS_COLETA (bairro, peso_kg) VALUES ('Centro', 150);
INSERT INTO TB_PONTOS_COLETA (bairro, peso_kg) VALUES ('Centro', 400);
INSERT INTO TB_PONTOS_COLETA (bairro, peso_kg) VALUES ('Vila Nova', 200);
INSERT INTO TB_PONTOS_COLETA (bairro, peso_kg) VALUES ('Centro', 1200);
COMMIT;